name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.5

      - name: Fetch deps
        run: |
          # Hosted with Git LFS.  See ./contrib/deps-bundle.sh
          wget -q https://github.com/firedancer-io/radiance/raw/deps/deps-bundle.tar.zst
          tar -I zstd -xf deps-bundle.tar.zst

      - name: Vet
        run: source activate-opt && go vet ./...

      - name: Build
        run: source activate-opt && go build -v ./cmd/radiance
